# netlify.toml

[build]
  command = "npm run build"  # Comando para construir tu aplicación
  publish = "dist"           # Directorio donde se encuentra la versión compilada de tu aplicación

[[redirects]]                # Configuración de redireccionamiento (opcional)
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]                  # Configuración de encabezados (opcional)
  for = "/*"
    [headers.values]
      X-Frame-Options = "DENY"
